# Generated by Django 5.2.1 on 2025-05-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_tag_project_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pictures',
        ),
    ]
