# Generated by Django 5.2.1 on 2025-06-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_donation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreport',
            unique_together=set(),
        ),
    ]
