# Generated by Django 5.2.1 on 2025-06-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_commentreport_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together=set(),
        ),
    ]
