# Generated by Django 5.2.1 on 2025-06-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_projectrating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectreport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together={('user', 'project')},
        ),
    ]
