# Generated by Django 5.2.1 on 2025-06-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customuser_is_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreport',
            unique_together={('comment', 'reporter')},
        ),
        migrations.AlterUniqueTogether(
            name='projectreport',
            unique_together={('project', 'reporter')},
        ),
    ]
