from django.urls import path
from .views import (
    CustomUserAPIView,
    RegisterView,
    ActivateAccountView,
    ResendActivationEmailView,
    GoogleAuthView,
    UserProfileView,
    ProjectCreateView,
    ProjectAPIView,
    CategoryListView,
    ProjectRateAPIView,
    ProjectAddCommentAPIView,
    CommentAddReplyAPIView,
    ProjectDonateAPIView,
    ProjectReportView,
    UserListView,
    UserDetailView,
    CommentReportView,
    LogoutView,
    ProjectRatingView,
    UserProjectRatingView,
    CancelProjectAPIView,
    DonateToProject,
    UserDonationAmount,
    PasswordResetRequestView,
    PasswordResetConfirmView,
)

urlpatterns = [
    path("users/", CustomUserAPIView.as_view(), name="users"),
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate"),
    path(
        "resend-activation/",
        ResendActivationEmailView.as_view(),
        name="resend_activation",
    ),
    path("google-login/", GoogleAuthView.as_view(), name="google_login"),
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path("projects/create/", ProjectCreateView.as_view(), name="project_create"),
    path("projects/", ProjectAPIView.as_view(), name="projects"),
    path("projects/<int:id>/", ProjectAPIView.as_view(), name="project_detail"),
    path("categories/", CategoryListView.as_view(), name="categories"),
    path("projects/<int:id>/rate/", ProjectRateAPIView.as_view(), name="project_rate"),
    path(
        "projects/<int:project_id>/comment/",
        ProjectAddCommentAPIView.as_view(),
        name="project_comment",
    ),
    path(
        "comments/<int:comment_id>/reply/",
        CommentAddReplyAPIView.as_view(),
        name="comment_reply",
    ),
    path(
        "projects/<int:id>/donate/",
        ProjectDonateAPIView.as_view(),
        name="project_donate",
    ),
    path(
        "projects/<int:project_id>/report/",
        ProjectReportView.as_view(),
        name="project_report",
    ),
    path("users/list/", UserListView.as_view(), name="user_list"),
    path("users/<int:id>/", UserDetailView.as_view(), name="user_detail"),
    path(
        "comments/<int:comment_id>/report/",
        CommentReportView.as_view(),
        name="comment_report",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "projects/<int:pk>/rating/", ProjectRatingView.as_view(), name="project_rating"
    ),
    path(
        "projects/<int:project_id>/user-rating/",
        UserProjectRatingView.as_view(),
        name="user_project_rating",
    ),
    path(
        "projects/<int:pk>/cancel/",
        CancelProjectAPIView.as_view(),
        name="cancel_project",
    ),
    path(
        "projects/<int:project_id>/donate/",
        DonateToProject.as_view(),
        name="donate_to_project",
    ),
    path(
        "projects/<int:project_id>/donation-amount/",
        UserDonationAmount.as_view(),
        name="user_donation_amount",
    ),
    path(
        "auth/password/reset/",
        PasswordResetRequestView.as_view(),
        name="password_reset",
    ),
    path(
        "auth/password/reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]
